### ISSUE TITLE
Where is the df08_rul_reg.csv file generated

### ISSUE THREAD

**Issue by a76yyyy** [darrahts/phm2021_data_challenge#1]
I see in this ipynb file that I need to load `df08_rul_reg.csv`, but I don't know where the file generation script is?

And the contents of these ipynb files look very cluttered, do you still organize them?

**Comment by darrahts** [comment]
Which notebook are you referring to ["this ipynb file"]? 

Also, yes, I actually need to remove most of these notebooks, you are correct they are a cluster. Please follow the [readme document](https://github.com/darrahts/phm2021_data_challenge#readme) as that is what is most up to date and working, everything else is sort of loose ends from previous work. Had some personal things come up and I have been delayed in returning to this project.
